=== Test: signature_key_generation ===
Date: Wed May 28 02:22:34 EDT 2025
Command: cd /home/ubuntu/martsia_project/web_app && python3 -c "
from src.main import app, db
from src.models.user import User
from src.encryption.digital_signature import DigitalSignature
import json

with app.app_context():
    # Get test users
    users = User.query.all()
    
    for user in users:
        # Generate signature keys
        signature = DigitalSignature()
        public_key, private_key_encrypted = signature.generate_key_pair(str(user.id), 'password123')
        
        # Update user
        user.public_key = public_key
        user.private_key_encrypted = private_key_encrypted
        
        print(f'Generated keys for user: {user.username}')
        print(f'Public key length: {len(public_key)}')
        print(f'Encrypted private key length: {len(private_key_encrypted)}')
    
    db.session.commit()
    print('Signature keys generated successfully')
"
---
Traceback (most recent call last):
  File "<string>", line 14, in <module>
TypeError: DigitalSignature.generate_key_pair() takes from 1 to 2 positional arguments but 3 were given
Exit status: 1
FAIL
